In [1]:
!python -V

Python 3.5.3 :: Anaconda custom (64-bit)


In [2]:
import numpy as np

np.__version__

'1.13.1'

Para consultar una función una vez dentro de los paréntesis, pulsar SHIFT + TAB

In [3]:
np.arange(2, 30, 5)

array([ 2,  7, 12, 17, 22, 27])

Para ejecutar una celda pulsamos CTRL + SHIFT + ENTER

In [17]:
x = np.linspace(0, 1, 21)
x

array([ 0.  ,  0.05,  0.1 ,  0.15,  0.2 ,  0.25,  0.3 ,  0.35,  0.4 ,
        0.45,  0.5 ,  0.55,  0.6 ,  0.65,  0.7 ,  0.75,  0.8 ,  0.85,
        0.9 ,  0.95,  1.  ])

In [18]:
x.shape

(21,)

In [8]:
y = np.array(['a', 'b', 'c'])
y

array(['a', 'b', 'c'],
      dtype='<U1')

In [10]:
y[0]

'a'

In [11]:
y[-1]

'c'

In [12]:
A = np.array([[1, 2, 3], [4, 5, 6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
A.shape

(2, 3)

In [14]:
A[0, 2]

3

In [15]:
A[1]

array([4, 5, 6])

In [16]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [19]:
x.reshape(3,7)

array([[ 0.  ,  0.05,  0.1 ,  0.15,  0.2 ,  0.25,  0.3 ],
       [ 0.35,  0.4 ,  0.45,  0.5 ,  0.55,  0.6 ,  0.65],
       [ 0.7 ,  0.75,  0.8 ,  0.85,  0.9 ,  0.95,  1.  ]])

In [20]:
x.reshape(3, -1)

array([[ 0.  ,  0.05,  0.1 ,  0.15,  0.2 ,  0.25,  0.3 ],
       [ 0.35,  0.4 ,  0.45,  0.5 ,  0.55,  0.6 ,  0.65],
       [ 0.7 ,  0.75,  0.8 ,  0.85,  0.9 ,  0.95,  1.  ]])

In [21]:
A.ravel()

array([1, 2, 3, 4, 5, 6])

In [22]:
A.ndim

2

In [23]:
x.ndim

1

In [25]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
np.max(A), np.min(A), np.sum(A), np.mean(A)

(6, 1, 21, 3.5)

In [28]:
np.log(A)

array([[ 0.        ,  0.69314718,  1.09861229],
       [ 1.38629436,  1.60943791,  1.79175947]])

In [29]:
np.exp(A)

array([[   2.71828183,    7.3890561 ,   20.08553692],
       [  54.59815003,  148.4131591 ,  403.42879349]])

In [30]:
np.max(A, axis=1)

array([3, 6])

In [31]:
np.max(A, axis=0)

array([4, 5, 6])

In [33]:
np.argmax(x)

20

In [34]:
A - A

array([[0, 0, 0],
       [0, 0, 0]])

In [35]:
A * 5

array([[ 5, 10, 15],
       [20, 25, 30]])

In [36]:
np.dot(A, A.T)

array([[14, 32],
       [32, 77]])

In [37]:
np.dot(A.T, A)

array([[17, 22, 27],
       [22, 29, 36],
       [27, 36, 45]])

In [39]:
np.mean(np.square(A), axis=1)

array([  4.66666667,  25.66666667])