# Notebooks



Esto es una celda de Markdown por eso su borde izquierdo es azul
# Esto es un título grande
## Esto es un título más pequeño
### Esto es un título aún más pequeño
*Esto está en cursiva*

**Esto está en negrita**

Esto es una enumeración:
1. qwe
2. ert

Esto es una lista de objetos no numerados:
- qwe
- ert

Esto es una fórmula de Latex:
$$p(x)=\sum_{i=1}^n \dfrac{1}{n} \int \log x dx$$

Para ejecutra esta celda pulsa **CTRL+ENTER** Ó **SHIFT+ENTER** si quieres seguir con la siguiente tras ejecutarla.
Es cómodo e importante conocer los shortcuts cuyo enlace se ha dado antes

In [1]:
#esto es una celda de código, por eso su borde es verde
3**2,5+7,[5,7]*4

(9, 12, [5, 7, 5, 7, 5, 7, 5, 7])

In [2]:
#comprobamos la versión de python
!python -V

Python 3.5.3 :: Anaconda custom (64-bit)


In [3]:
%pwd # en qué carpeta estamos

'/home/infinitemonkeys/Documents/EOI Tenerife/Tema 1/Sección 1/notebooks'

# Numpy

In [4]:
import numpy as np
print('buenas')
np.arange(1,10,0.5)**2

buenas


array([  1.  ,   2.25,   4.  ,   6.25,   9.  ,  12.25,  16.  ,  20.25,
        25.  ,  30.25,  36.  ,  42.25,  49.  ,  56.25,  64.  ,  72.25,
        81.  ,  90.25])

In [5]:
A=np.array([[1.1,2.7],[3/9,4.123],[5,6]],dtype=np.int64)
print(A)
print(A.shape)
print(A[2,])
print(A[:,1])
print(A[2,1])

[[1 2]
 [0 4]
 [5 6]]
(3, 2)
[5 6]
[2 4 6]
6


In [6]:
A.dtype

dtype('int64')

In [7]:
A.ndim

2

In [8]:
A=np.array([[1.1,2.7],[3/9,4.123],[5,6]])
print(A.dtype)
A

float64


array([[ 1.1       ,  2.7       ],
       [ 0.33333333,  4.123     ],
       [ 5.        ,  6.        ]])

In [9]:
A.astype('int')

array([[1, 2],
       [0, 4],
       [5, 6]])

In [10]:
A*A

array([[  1.21      ,   7.29      ],
       [  0.11111111,  16.999129  ],
       [ 25.        ,  36.        ]])

In [11]:
1/A

array([[ 0.90909091,  0.37037037],
       [ 3.        ,  0.24254184],
       [ 0.2       ,  0.16666667]])

In [12]:
A-A

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [13]:
A**2

array([[  1.21      ,   7.29      ],
       [  0.11111111,  16.999129  ],
       [ 25.        ,  36.        ]])

In [14]:
print(A.reshape(2,3))
print()
print(A.T)
print()
B=np.dot(A.T,A) #producto matricial
print(B)
print()
print(B.shape)

[[ 1.1         2.7         0.33333333]
 [ 4.123       5.          6.        ]]

[[ 1.1         0.33333333  5.        ]
 [ 2.7         4.123       6.        ]]

[[ 26.32111111  34.34433333]
 [ 34.34433333  60.289129  ]]

(2, 2)


In [15]:
A.ravel()

array([ 1.1       ,  2.7       ,  0.33333333,  4.123     ,  5.        ,  6.        ])

In [16]:
H=np.random.randn(4,3,4)
print(H.shape)
print()
print(H.ndim)

(4, 3, 4)

3


In [17]:
#generadores de arrays
print(np.linspace(0,10,21))
print()
print(np.arange(0,10,0.5))
print()
print(np.zeros((3,2)))
print()
print(np.ones((2,7)))
print()
print(np.logspace(-3,5,10))

[  0.    0.5   1.    1.5   2.    2.5   3.    3.5   4.    4.5   5.    5.5
   6.    6.5   7.    7.5   8.    8.5   9.    9.5  10. ]

[ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.
  7.5  8.   8.5  9.   9.5]

[[ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]]

[[ 1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.]]

[  1.00000000e-03   7.74263683e-03   5.99484250e-02   4.64158883e-01
   3.59381366e+00   2.78255940e+01   2.15443469e+02   1.66810054e+03
   1.29154967e+04   1.00000000e+05]


In [18]:
C = np.array( [[1,1],[0,1]] )
B = np.array( [[2,0],[3,4]] )
C*B                         # producto elemento por elemento

array([[2, 0],
       [0, 4]])

Las funciones están en https://docs.scipy.org/doc/numpy/reference/routines.math.html

In [19]:
print(A)
print()
print(np.cos(A),np.exp(A),np.log(A),np.log10(A),np.log1p(A))
print()
print(A**2)
print()
print(A+1)

[[ 1.1         2.7       ]
 [ 0.33333333  4.123     ]
 [ 5.          6.        ]]

[[ 0.45359612 -0.90407214]
 [ 0.94495695 -0.5558532 ]
 [ 0.28366219  0.96017029]] [[   3.00416602   14.87973172]
 [   1.39561243   61.74419729]
 [ 148.4131591   403.42879349]] [[ 0.09531018  0.99325177]
 [-1.09861229  1.41658105]
 [ 1.60943791  1.79175947]] [[ 0.04139269  0.43136376]
 [-0.47712125  0.61521333]
 [ 0.69897     0.77815125]] [[ 0.74193734  1.30833282]
 [ 0.28768207  1.6337402 ]
 [ 1.79175947  1.94591015]]

[[  1.21         7.29      ]
 [  0.11111111  16.999129  ]
 [ 25.          36.        ]]

[[ 2.1         3.7       ]
 [ 1.33333333  5.123     ]
 [ 6.          7.        ]]


In [20]:
print(np.random.random((2,5)))

[[ 0.0525907   0.88369265  0.85656195  0.22445899  0.85864392]
 [ 0.18497874  0.88089774  0.17358295  0.42557249  0.6096382 ]]


Definimos la función $f(x)=\dfrac{1}{1+\exp{-x}}$ y la aplicamos en la matriz $A$ aplicando previamente la vectorzación con `np.vectorize`

In [21]:
def mifunc(x):
    return 1/(1+np.exp(-x))

mifunc(3)

0.95257412682243336

In [22]:
#vectorizamos y así se convierte en una función broadcast
mifuncvec=np.vectorize(mifunc)
mifuncvec(A)

array([[ 0.75026011,  0.93702664],
       [ 0.58257021,  0.98406227],
       [ 0.99330715,  0.99752738]])

In [23]:
print(np.pi)
print(np.e)

3.141592653589793
2.718281828459045


In [24]:
[ mifunc(x) for x in np.arange(1,4,0.5)]

[0.7310585786300049,
 0.81757447619364365,
 0.88079707797788231,
 0.92414181997875655,
 0.95257412682243336,
 0.97068776924864364]

In [25]:
x=np.array([1,3,5,2,4,3,7])
x>2

array([False,  True,  True, False,  True,  True,  True], dtype=bool)

In [26]:
x[x>2]

array([3, 5, 4, 3, 7])

In [27]:
np.where(x>2)

(array([1, 2, 4, 5, 6]),)

In [28]:
x[np.where(x>2)]

array([3, 5, 4, 3, 7])

### Funciones integradas

|Function Name      |   NaN-safe Version  | Description                                   |
|-------------------|---------------------|-----------------------------------------------|
| ``np.sum``        | ``np.nansum``       | Compute sum of elements                       |
| ``np.prod``       | ``np.nanprod``      | Compute product of elements                   |
| ``np.mean``       | ``np.nanmean``      | Compute median of elements                    |
| ``np.std``        | ``np.nanstd``       | Compute standard deviation                    |
| ``np.var``        | ``np.nanvar``       | Compute variance                              |
| ``np.min``        | ``np.nanmin``       | Find minimum value                            |
| ``np.max``        | ``np.nanmax``       | Find maximum value                            |
| ``np.argmin``     | ``np.nanargmin``    | Find index of minimum value                   |
| ``np.argmax``     | ``np.nanargmax``    | Find index of maximum value                   |
| ``np.median``     | ``np.nanmedian``    | Compute median of elements                    |
| ``np.percentile`` | ``np.nanpercentile``| Compute rank-based statistics of elements     |
| ``np.any``        | N/A                 | Evaluate whether any elements are true        |
| ``np.all``        | N/A                 | Evaluate whether all elements are true        |

In [29]:
np.max(x),np.argmax(x)

(7, 6)

In [30]:
np.min(x), np.argmin(x)

(1, 0)

In [31]:
np.abs(x)

array([1, 3, 5, 2, 4, 3, 7])

In [32]:
np.sign(x)

array([1, 1, 1, 1, 1, 1, 1])

In [33]:
np.all(x<2)

False

In [34]:
np.isclose(x,x+0.5e-4)

array([False, False,  True, False, False, False,  True], dtype=bool)

In [35]:
np.isclose([1.1,0.9],[1,1])

array([False, False], dtype=bool)

In [36]:
np.isclose([1.000001,0.9999],[1,1])

array([ True, False], dtype=bool)

In [37]:
np.unique(x,return_counts=True)

(array([1, 2, 3, 4, 5, 7]), array([1, 1, 2, 1, 1, 1]))

In [38]:
np.bincount(np.arange(5))

array([1, 1, 1, 1, 1])

In [39]:
np.bincount(np.array([0, 1, 1, 3, 2, 1, 7]))

array([1, 3, 1, 1, 0, 0, 0, 1])

In [40]:
np.cumsum(x)

array([ 1,  4,  9, 11, 15, 18, 25])

In [41]:
np.cumprod(x)

array([   1,    3,   15,   30,  120,  360, 2520])

In [42]:
#aplicamos sobre matrices siguiendo un eje ó una condición
A=np.arange(1,21).reshape(4,5)
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [43]:
np.sum(A,axis=0)

array([34, 38, 42, 46, 50])

In [44]:
np.sum(A>6,axis=1)

array([0, 4, 5, 5])

In [45]:
np.max(A,axis=1)

array([ 5, 10, 15, 20])

In [46]:
np.any(A>=19,axis=0)

array([False, False, False,  True,  True], dtype=bool)

# Evaluadores booleanos y ecuaciones

In [47]:
np.any([True,False,True])

True

In [48]:
np.all([True,False]), np.all([True,True])

(False, True)

### Algunas funciones estadísticas

In [49]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [50]:
np.mean(A)

10.5

In [51]:
np.mean(A,axis=0)

array([  8.5,   9.5,  10.5,  11.5,  12.5])

In [52]:
np.mean(A,axis=1)

array([  3.,   8.,  13.,  18.])

In [53]:
np.std(A,axis=0),np.std(A,axis=1)

(array([ 5.59016994,  5.59016994,  5.59016994,  5.59016994,  5.59016994]),
 array([ 1.41421356,  1.41421356,  1.41421356,  1.41421356]))

In [54]:
np.median(A,axis=0),np.median(A,axis=1)

(array([  8.5,   9.5,  10.5,  11.5,  12.5]), array([  3.,   8.,  13.,  18.]))

In [55]:
np.percentile(A,[0.1,0.9],axis=0) , np.percentile(A,[0.1,0.9],axis=0)

(array([[ 1.015,  2.015,  3.015,  4.015,  5.015],
        [ 1.135,  2.135,  3.135,  4.135,  5.135]]),
 array([[ 1.015,  2.015,  3.015,  4.015,  5.015],
        [ 1.135,  2.135,  3.135,  4.135,  5.135]]))

### Operaciones entre arrays broadcast

<img src='02.05-broadcasting.png'>


Reglas de interacción entre arrays:

1. Si los dos arrays tienen diferentes dimensiones, se rellena la dimensión del que sea inferior con unos por el lado izquierdo.
2. Si ninguna dimensión de los dos arrays coincide, el que tenga alguna dimensión igual a 1 se reajusta para casa con las dimensiones del otro array. 
3. Si ninguna de las dimensiones coincide y ninguno de los arrays tiene una dimensión igual a 1 salta un error.

In [56]:
a = np.arange(3).reshape((3, 1))
b = np.arange(3)
print(a, '\n')
print(b,'\n')
a.shape,b.shape

[[0]
 [1]
 [2]] 

[0 1 2] 



((3, 1), (3,))

In [57]:
a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [58]:
M = np.ones((3, 2))
a = np.arange(3)
print(a, '\n')
print(M,'\n')
a.shape,M.shape

[0 1 2] 

[[ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]] 



((3,), (3, 2))

In [59]:
M+a

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

In [ ]:
A=np.arange(0,20).reshape(4,5)
A

In [ ]:
B=np.array([3,2,1,4])
C=np.array([-1,0,-1,0,-1])

In [ ]:
A+C

In [ ]:
A+B.reshape(4,1)

In [ ]:
C+B.reshape(4,1)

In [ ]:
A*C  

In [ ]:
np.sum(A,axis=0)

In [ ]:
np.sum(A,axis=1)

## Unión y división  de arrays

In [60]:
M=np.array([[1,2,3],[4,5,6]])
M

array([[1, 2, 3],
       [4, 5, 6]])

In [61]:
N=np.array([[7,8,9],[10,11,12]])
N

array([[ 7,  8,  9],
       [10, 11, 12]])

In [62]:
np.hstack((M,N))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [63]:
H=np.vstack((M,N))
H

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [64]:
np.hsplit(H,[2])

[array([[ 1,  2],
        [ 4,  5],
        [ 7,  8],
        [10, 11]]), array([[ 3],
        [ 6],
        [ 9],
        [12]])]

In [65]:
np.vsplit(H,[2,4])

[array([[1, 2, 3],
        [4, 5, 6]]), array([[ 7,  8,  9],
        [10, 11, 12]]), array([], shape=(0, 3), dtype=int64)]

## Indexación

In [66]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [67]:
A[3] #última fila

array([16, 17, 18, 19, 20])

In [68]:
A[3,:]

array([16, 17, 18, 19, 20])

In [69]:
A[:,2] #tercera columna

array([ 3,  8, 13, 18])

In [70]:
A[-1] #última fila

array([16, 17, 18, 19, 20])

In [71]:
A[1,3] #posición 2x4

9

In [72]:
A[:2,1:]

array([[ 2,  3,  4,  5],
       [ 7,  8,  9, 10]])

In [73]:
A[1:3,:2]

array([[ 6,  7],
       [11, 12]])

In [74]:
(A>5) & (A<12) #índices usando booleanos

array([[False, False, False, False, False],
       [ True,  True,  True,  True,  True],
       [ True, False, False, False, False],
       [False, False, False, False, False]], dtype=bool)

In [75]:
A[(A>5) & (A<12)]

array([ 6,  7,  8,  9, 10, 11])

In [76]:
arr = np.arange(10)
print(arr)
print()

arr[5:8] = 12
print(arr)

[0 1 2 3 4 5 6 7 8 9]

[ 0  1  2  3  4 12 12 12  8  9]


In [77]:
#array 2 dimensional
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d[2])
print()
print(arr2d[0][2])
print()
print(arr2d[0, 2])

[7 8 9]

3

3


In [78]:
#array 3 dimensional
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9],
[10, 11, 12]]])
print(arr3d,'\n')

print(arr3d.shape,'\n')

print(arr3d[0],'\n')


old_values = arr3d[0].copy()
arr3d[0] = 42
print(arr3d[1, 0])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]] 

(2, 2, 3) 

[[1 2 3]
 [4 5 6]] 

[7 8 9]


In [79]:
#indexación usando booleanos que pueden proceder de otros arrays relacionados con la misma dimensión
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will','Joe', 'Joe'])
data = np.random.randn(7, 4)
data.shape

(7, 4)

In [80]:
names == 'Bob'

array([ True, False, False,  True, False, False, False], dtype=bool)

In [81]:
data[names == 'Bob'] #devuelve las dos filas de Bob en la matriz original

array([[ 0.7760538 , -1.47856156,  0.12847673, -2.34635478],
       [ 1.02849005,  0.06927661, -0.82497564, -1.43992956]])

In [82]:
data[names == 'Bob', 2:]

array([[ 0.12847673, -2.34635478],
       [-0.82497564, -1.43992956]])

In [83]:
data[names == 'Bob', 3]

array([-2.34635478, -1.43992956])

In [84]:
names != 'Bob' 

array([False,  True,  True, False,  True,  True,  True], dtype=bool)

In [85]:
mask = (names == 'Bob') | (names == 'Will')
mask

array([ True, False,  True,  True,  True, False, False], dtype=bool)

In [86]:
data[mask]

array([[ 0.7760538 , -1.47856156,  0.12847673, -2.34635478],
       [-0.09315312,  1.02481914, -1.52727309, -1.6213458 ],
       [ 1.02849005,  0.06927661, -0.82497564, -1.43992956],
       [-0.36687144,  0.96889311, -0.25302891, -0.01094387]])

In [87]:
data[names != 'Joe'] = 7 #modificamos las posiciones que cumplen el booleano

In [88]:
data

array([[  7.00000000e+00,   7.00000000e+00,   7.00000000e+00,
          7.00000000e+00],
       [  9.53745448e-02,  -1.48143722e+00,  -1.11195342e+00,
          1.11085572e-01],
       [  7.00000000e+00,   7.00000000e+00,   7.00000000e+00,
          7.00000000e+00],
       [  7.00000000e+00,   7.00000000e+00,   7.00000000e+00,
          7.00000000e+00],
       [  7.00000000e+00,   7.00000000e+00,   7.00000000e+00,
          7.00000000e+00],
       [ -2.13277623e-01,   6.22547482e-01,   7.44515953e-01,
         -1.52628038e-03],
       [  1.33157063e+00,   2.92798875e-01,  -5.97082335e-01,
          5.99959976e-01]])

In [89]:
X = np.arange(12).reshape((3, 4))
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [90]:
row = np.array([0, 1, 2])
col = np.array([2, 1, 3])
X[row, col]

array([ 2,  5, 11])

# Ordenando arrays

In [91]:
x = np.array([2, 5, 4, 1, -7])
np.sort(x),np.flipud(np.sort(x))

(array([-7,  1,  2,  4,  5]), array([ 5,  4,  2,  1, -7]))

In [92]:
np.argsort(x)

array([4, 3, 0, 2, 1])

In [93]:
np.argsort(x)

array([4, 3, 0, 2, 1])

In [94]:
x.sort() #hace sort in-place
x

array([-7,  1,  2,  4,  5])

In [95]:
X = np.arange(12).reshape((3, 4))
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [96]:
np.sort(X,axis=1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [97]:
np.sort(-X,axis=0)

array([[ -8,  -9, -10, -11],
       [ -4,  -5,  -6,  -7],
       [  0,  -1,  -2,  -3]])

## Guardar y cargar  una matriz




In [98]:
np.save('matrizA.npy', A)

In [99]:
np.load('matrizA.npy')

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

# Definiendo funciones y clases



In [100]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [101]:
def factorial(n):   #se declara el nombre de la función y sus argumentos
    c=np.prod(np.arange(1,n+1))  #en formato indentado se realizan las operaciones
    return c #el valor a devolver

#esto es un ejemplo con bucles dentro
def fibonacci(n):
    if n==1 or n==2:
        c=1
    else:
        a0=1
        a1=1
        for k in range(n-1):
            aux=a0+a1
            a0=a1
            a1=aux
        c=a1
    
    return c

In [102]:
factorial(6)

720

In [103]:
fibonacci(5)

8

Definimos una clase para la función de densidad y de distribución de la variable aleatoria exponencial
$$\begin{align*} 
f_\lambda (x) &=\lambda \mathrm{e}^{-\lambda x}\\
F_\lambda (x) &=1-\mathrm{e}^{-\lambda x} \end{align*}$$

In [104]:
class exponencial():    
    #esta es la partícula inicial que almacena los parámetros necesarios en la clase
    def __init__(self,lamb): 
        self.lamb=lamb
    
    #definimos los métodos, se puede llamar a los parámetros almacenados en __init__     
    def dens(self,x):
        import numpy as np
        lamb=self.lamb
        return  lamb*np.exp(-lamb*x)
    
    def dist(self,x):
        import numpy as np
        lamb=self.lamb
        return  1-np.exp(-lamb*x)

In [105]:
fexp=exponencial(2) #define una instancia de la clase con el parámetro lambda=3
fexp.dens(4),fexp.dist(1) #aplica ambos métodos sobre el valor dado

(0.00067092525580502371, 0.8646647167633873)

Se puede vectorizar una función escalar para hacer broadcast con `numpy.vectorize`

In [106]:
fibvec=np.vectorize(fibonacci)

A=np.arange(350,10000,15).reshape(4,161)
print(A.shape)

fibvec(A)[:3]

(4, 161)


array([[ 10119911756749018713965376799211044556615579094364594923736162239653346274,
        13803567055491817972029187936825113333650564850089197542855968899086435571688,
        18828075583602596462866526311206253798143927071100759813050465314516137773128706,
        25681508899600997067167913917673267005781650175546286474198377544968911008983126672,
        35029596967131343602213497450232647402139968983372205851566400021802909132390757909314,
        47780395944676052274416277690031248729785923474969864327823043828116713025492002771430968,
        65172495098135102433647404982700073500075401759827878315356483347951218369680224170989749666,
        88895331094252224395547334812680590285351577786328700992010571109649289972956851261232789975392,
        121253296785055132210628998331901307849293052175954107980980734350044979474331514800545696516184354,
        165389585710146294587522349272048196587026008519579189614758713664032461652278159144795591280865434248,
        22559151616193

# ACTIVIDAD

Definir una función `sigmoide` y vectorízala
$$f(x)=\dfrac{1}{1+\mathrm{e}^{-x}}$$


In [107]:
def sigmoide(x):
    import numpy as np
    return 1/(1+np.exp(-x))

sigvec=np.vectorize(sigmoide)

In [108]:
sigvec([4,-3,1])

array([ 0.98201379,  0.04742587,  0.73105858])

# ACTIVIDAD

Definir una función `npositivos(l)`que reciba un array numpy y devuelva el número de elementos positivos del mismo.

Por ejemplo:

`npositivos([-2,2,1,-3,2,5,-6,4,5,2,-8])` daría como resultado `7`


In [109]:
#solución
def npositivos(l):
    acum=0
    for x in l:
        if x>0:
            acum+=1
    return acum

npositivos([-2,2,1,-3,2,5,-6,4,5,2,-8])

7

# ACTIVIDAD 

- Genera una matriz 5x4 con números de 0 a 4 con pasos de 0.2
- Intercambia las filas 0 y 3
- Toma la exponencial de todos sus elementos. Devuelve los valores que superan 1.1
- Construye un vector aleatorio con 200 posiciones enteras entre -5 y 5 usando `numpy.random.randint`. A continuación define una función que toma los $k$ últimos elementos y los suma, generando así una **suma móvil**

In [110]:
# solución
#generamos la matriz
A = np.arange(0,4,0.2).reshape(5,4)
#intercambiamos
A[[0,3]] = A[[3,0]]
print(A)

[[ 2.4  2.6  2.8  3. ]
 [ 0.8  1.   1.2  1.4]
 [ 1.6  1.8  2.   2.2]
 [ 0.   0.2  0.4  0.6]
 [ 3.2  3.4  3.6  3.8]]


In [111]:
np.exp(A)

array([[ 11.02317638,  13.46373804,  16.44464677,  20.08553692],
       [  2.22554093,   2.71828183,   3.32011692,   4.05519997],
       [  4.95303242,   6.04964746,   7.3890561 ,   9.0250135 ],
       [  1.        ,   1.22140276,   1.4918247 ,   1.8221188 ],
       [ 24.5325302 ,  29.96410005,  36.59823444,  44.70118449]])

In [112]:
A[np.exp(A)>1]

array([ 2.4,  2.6,  2.8,  3. ,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,
        2.2,  0.2,  0.4,  0.6,  3.2,  3.4,  3.6,  3.8])

In [113]:
vec=np.random.randint(-5,5,200)

def sumamovil(a, n) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] 

In [114]:
vec

array([ 0,  4, -2,  3,  2, -2, -5, -4, -5, -3,  4, -3,  4,  2, -5,  0,  4,
        0,  0, -5, -5,  2, -5, -4,  1, -5,  3, -4,  0,  3,  3, -5, -2, -5,
        1, -2, -4, -3, -5,  2,  2,  0, -2,  2,  4,  2,  0, -1, -2,  2,  3,
       -5, -1,  0, -3,  1, -1,  1,  0,  0,  0, -4,  0, -5,  1,  1,  0, -2,
        1,  0,  0,  3,  4,  4,  4, -5,  3, -5, -3, -3,  1,  0,  2,  4, -2,
        4,  1, -1, -4, -3, -1,  2, -1,  3, -2,  3, -4, -2,  0,  4, -5,  0,
        3, -3,  3, -2, -4, -3,  3,  3,  0,  4,  1, -3,  4,  2,  0,  1, -2,
        4, -2,  3,  0,  1, -4, -2, -4, -5, -4, -4, -5,  2,  2,  3,  1, -1,
       -3, -1, -4,  3,  2, -5,  3, -4,  0,  3, -1, -5, -1, -1, -5,  0, -1,
       -2, -1, -2,  3,  4,  0, -1, -2, -4,  1,  3, -3,  0, -1, -2,  0,  3,
       -4, -2, -4,  0, -1, -2,  3,  3, -4,  0,  2, -2,  4,  3,  2, -1,  1,
        4,  0,  2, -4, -5, -4,  2,  4,  2,  0,  3, -4, -5])

In [115]:
sumamovil(vec, 4)

array([  5.,   7.,   1.,  -2.,  -9., -16., -17.,  -8.,  -7.,   2.,   7.,
        -2.,   1.,   1.,  -1.,   4.,  -1., -10.,  -8., -13., -12.,  -6.,
       -13.,  -5.,  -5.,  -6.,   2.,   2.,   1.,  -1.,  -9., -11.,  -8.,
       -10.,  -8., -14., -10.,  -4.,  -1.,   2.,   2.,   4.,   6.,   8.,
         5.,  -1.,  -1.,   2.,  -2.,  -1.,  -3.,  -9.,  -3.,  -3.,  -2.,
         1.,   0.,   1.,  -4.,  -4.,  -9.,  -8.,  -3.,  -3.,   0.,   0.,
        -1.,  -1.,   4.,   7.,  11.,  15.,   7.,   6.,  -3., -10.,  -8.,
       -10.,  -5.,   0.,   7.,   4.,   8.,   7.,   2.,   0.,  -7.,  -9.,
        -6.,  -3.,   3.,   2.,   3.,   0.,  -5.,  -3.,  -2.,  -3.,  -1.,
         2.,  -5.,   3.,   1.,  -6.,  -6.,  -6.,  -1.,   3.,  10.,   8.,
         2.,   6.,   4.,   3.,   7.,   1.,   3.,   1.,   3.,   5.,   2.,
         0.,  -5.,  -9., -15., -15., -17., -18., -11.,  -5.,   2.,   8.,
         5.,   0.,  -4.,  -9.,  -5.,   0.,  -4.,   3.,  -4.,  -6.,   2.,
        -2.,  -3.,  -4.,  -8., -12.,  -7.,  -7.,  -

## ACTIVIDAD

Define una clase polinómica que :
- Se inicie con un número $n$ indicando el grado del polinomio.
- Tenga un método que recibe una lista ó array con $n+1$ números que son los coeficientes del polinomio $[a_0,a_1,\dots,a_n]$ de grado $n$ y los guarde:
$$p(x)=\sum_{k=0}^n a_k x^k$$
-  Tenga un método `__call__` que dado una entrada escalar devuelva el valor del polinomio.
-  Tenga un método `deriva` que deriva el polinomio, cambiando la instancia clase a un orden menos derivándolo a 
$$p'(x)=\sum_{k=1}^n ka_k x^{k-1}$$
- Tenga un método que 

In [116]:
np.hstack((1,np.repeat(2,5)))

array([1, 2, 2, 2, 2, 2])

In [117]:
np.cumprod(np.hstack((1,np.repeat(2,5))))

array([ 1,  2,  4,  8, 16, 32])

In [118]:
class polinomio():
    def __init__(self,n):
        self.n=n
        self.coefs=None
        
    def set_coef(self,listan):
        assert len(listan)==(self.n+1),' El número de coeficientes no es correcto'
        self.coefs=listan
        
    def __call__(self,x):
        assert self.coefs!=None, ' No hay coeficientes definidos'
        import numpy as np
        xx=np.cumprod(np.hstack((1,np.repeat(x,self.n))))            
       
        return np.dot(xx,self.coefs)
    def deriva(self):
        n=self.n
        self.n=self.n-1
        listacoefs=self.coefs[1:]
        self.coefs=np.arange(1,n+1)*listacoefs        

In [119]:
pol=polinomio(4)
pol.set_coef([1,0,5,7,8])

In [120]:
pol.n

4

In [121]:
pol.coefs, pol.coefs[1:]

([1, 0, 5, 7, 8], [0, 5, 7, 8])

In [122]:
pol(3)

883

In [123]:
pol.deriva()

In [124]:
pol.n,pol.coefs

(3, array([ 0, 10, 21, 32]))

In [125]:
pol.deriva()

In [126]:
pol.n,pol.coefs

(2, array([10, 42, 96]))

# Generadores de números aleatorios

https://docs.scipy.org/doc/numpy/reference/routines.random.html


In [127]:
x=np.linspace(0,10,7)
x

array([  0.        ,   1.66666667,   3.33333333,   5.        ,
         6.66666667,   8.33333333,  10.        ])

In [128]:
np.random.shuffle(x) #barajamos el vector, se hace inplace
x

array([  3.33333333,   6.66666667,   1.66666667,   5.        ,
        10.        ,   8.33333333,   0.        ])

In [129]:
np.random.rand(3,2) #números aleatorios entre 0 y 1 uno con la dimensión indicada

array([[ 0.58381865,  0.35949598],
       [ 0.18117372,  0.17061965],
       [ 0.54481785,  0.77835162]])

In [130]:
np.random.randn(4,2,2) #números aleatorios generados por la normal estándar N(0,1) con la dimensión solicitada

array([[[-0.17481071,  2.18735033],
        [ 0.67929765, -0.91187072]],

       [[-1.20676712, -0.21279773],
        [-0.76962441,  1.12643595]],

       [[ 0.40699421, -0.38963857],
        [-0.08078878, -0.54910822]],

       [[-1.25081315, -0.74748589],
        [ 0.78666492,  1.35111864]]])

In [131]:
#números aleatorios enteros generados en un intervalo establecido con la dimensión solicitada
np.random.randint(10,20,(3,))

array([18, 10, 19])

In [132]:
#3 números enteros elegidos aleatoriamente entre 0 y 4 incluyendo extremos
np.random.choice(5, 3)

array([3, 0, 1])

In [133]:
#igual que el anterior pero con probabilidades asignadas a cada númeroÇ
np.random.choice(5, 3, p=[0.2, 0, 0.3, 0.5, 0])

array([3, 0, 2])

In [134]:
#3 números enteros hasta el 9 seleccionados SIN reemplazamiento
np.random.choice(10, 5, replace=False)

array([7, 2, 6, 4, 3])

In [135]:
#5 muestras  de un array dado junto a sus probabilidades
aa_milne_arr = ['pooh', 'rabbit', 'piglet', 'Christopher']
np.random.choice(aa_milne_arr, 5, p=[0.5, 0.1, 0.1, 0.3])

array(['pooh', 'pooh', 'pooh', 'rabbit', 'rabbit'],
      dtype='<U11')

In [136]:
#np.random.seed(0)sirve para crear resultados reproducibles en el entrenamiento de modelos
for k in range(4):
    np.random.seed(0) 
    print(np.random.choice(10,5))

[5 0 3 3 7]
[5 0 3 3 7]
[5 0 3 3 7]
[5 0 3 3 7]


In [137]:
#observamos que sin random.seed los valores son distintos, además no lo recuerda del apartado anterior
for k in range(4):
    print(np.random.choice(10,5))

[9 3 5 2 4]
[7 6 8 8 1]
[6 7 7 8 1]
[5 9 8 9 4]


## ACTIVIDAD

**En todo el ejercicio se debe usar `np.random.seed(0)`para obtener resultados iguales**
1. Usando `np.random.rand` , crea una matriz 4x5 que tenga números aleatoriamente repartidos en el intervalo $[\pi,10]$. Da el valor máximo  por columnas así como en qué posiciones del array se tienen.
2. Crea otra  matriz M con dimensión 50x200 con los mismos valores.
A continuación define una función que realize la siguiente operación usando bucles, haz otra función que sólo use funciones numpy. 
        Resta a las columnas el vector que indica la fila de cada posición. Eleva el vector resultante al cuadrado y multiplícalo por filas. Haz la media del vector columna resultante.
        
Vamos a medir la diferencia de tiempo realizando la operación en ambos casos con `%timeit`, calculando el ratio entre los dos tiempos. Nuestro interés es observar la eficiencia del uso de las operaciones vectorizadas en `numpy`. **Recordamos que dichas operaciones trabajan a bajo nivel y de modo paralelo, lo que las hacen mucho más eficientes que la construcción de bucles**

In [138]:
#apartado 1
np.random.seed(0)
A=np.pi+(10-np.pi)*np.random.rand(4,5)
A

array([[ 6.90557922,  8.04665266,  7.27558942,  6.87862348,  6.04718984],
       [ 7.57139758,  6.142744  ,  9.25773515,  9.75078441,  5.77139078],
       [ 8.57156547,  6.76896946,  7.03747364,  9.48971144,  3.62878688],
       [ 3.73916088,  3.28025866,  8.85203872,  8.47850863,  9.10849036]])

In [139]:
np.max(A,axis=0)

array([ 8.57156547,  8.04665266,  9.25773515,  9.75078441,  9.10849036])

In [140]:
np.argmax(A,axis=0)

array([2, 0, 1, 1, 3])

Por tanto las posiciones del array en los que se tienen los máximos por columnas son (2,0),(0,1),(1,2),(1,3),(3,3)

In [141]:
#apartado 2
np.random.seed(0)
M=np.pi+(10-np.pi)*np.random.rand(50,200)

m,n=M.shape

In [142]:
def operabucle(M):
    import numpy as np
    m,n=M.shape
    res=np.arange(0,n)
    S=(M-res)**2
    v=np.zeros(m)
    for i in range(m):
        c=0
        for j in range(n):
            c*=S[i,j]
        v[i]=c
    d=0
    for i in range(m):
        d+=v[i]
    return d /m   

In [143]:
%timeit operabucle(M)

1000 loops, best of 3: 1.51 ms per loop


In [144]:
def operanp(M):
    import numpy as np
    m,n=M.shape
    return np.mean(np.prod((M-np.arange(0,n))**2,axis=1))

In [145]:
%timeit operanp(M)

10000 loops, best of 3: 34.6 µs per loop


In [146]:
1.31*10**3/30.6 #es 42 veces más rápido

42.810457516339866

# ACTIVIDAD

Define una función que haga un **random walk**